
dosbox.here_is_your_working_dir()
dosbox.title('DOS')
dosbox.window_resolution('1024x768')
dosbox.cpu_core('dynamic_x86')
dosbox.cpu_cycles('150000')
dosbox.integration_device('true')
dosbox.mouse_emulation('integration')
dosbox.mouse_wheel_key('1')
dosbox.isa_pnp_bios('false')
dosbox.isa_pnp_port('false')
dosbox.unmask_keyboard_on_int16_read('true')
dosbox.int13_fake_v86_io('false')
dosbox.xms('true')
dosbox.ems('true')
dosbox.umb('true')
dosbox.macaddr('AC:DE:48:01:01:01')
dosbox.config_sys('dos=high,umb')
dosbox.config_sys('lastdrive=z')
dosbox.autoexec_bat('imgmount c: .disk.vhd -t hdd')
dosbox.autoexec_bat('c:')
dosbox.autoexec_bat('call autoexec.bat')
dosbox.autoexec_bat("echo.") -- put some empty lines after AUTOEXEC.BAT output
dosbox.autoexec_bat("echo.")
dosbox.autoexec_bat("echo.")

local disk, DIR = mkdisk.create_named('C:', '.disk.vhd', '20m', 'fat16')
disk:add_directory(DIR['/'], 'disk_c')
